function About({ ds }) {
  const paragraphs = [
    'Every parent knows the moment. You hand your child a laptop for schoolwork, and ten minutes later it\'s YouTube. So you install a blocker — and now it blocks the biology chapter too, because to a crude filter, the human body and the wrong kind of website look the same. The child is angry, the parent is exhausted, and somewhere in the middle, the actual studying stopped being the point.',
    'We think the entire industry took a wrong turn at "Access Denied."',
    'A blocked page is not a dead end. It is a moment — a child, mid-curiosity, one click from distraction — and that moment is the most teachable second of the whole day. GuideRail was built on a single inversion: what if the wall was a door with a fair price on it? Three questions from what you read this morning. Answer them, and thirty minutes of free time is yours — earned, visible, honest. Not because we gamified discipline, but because we believe children respond to fairness the way all people do: when the deal is transparent, nobody needs to sneak, and nobody needs to shout.',
    'We believe the child is not the enemy. Most parental-control software is built like surveillance — it reads messages, tracks locations, reports everything to a cloud, and asks the child to accept being watched. We refuse the premise. No spying, no shouting: GuideRail never reads messages, never tracks location, and every rule that applies to a child is visible to that child, in plain language, always. A tool a child perceives as fair is a tool a child stops fighting.',
    'We believe privacy is architecture, not a promise. Your child\'s browsing is checked on the device itself, by a small engine that works even without internet. Nothing to upload means nothing to leak, nothing to subpoena, nothing to trust us about. Where AI helps — writing quiz questions, building worksheets — every name, number, and address is scrubbed out on the device before a single word leaves it, and every AI-written question must prove itself against the page your child actually read, or it is discarded. We built the honesty into the machine so it doesn\'t depend on our good behavior.',
    'We believe in guide rails, not gates. The name is the philosophy. A gate stops you. A guide rail runs alongside a mountain road — it lets you travel fast and far, and simply keeps you from going over the edge. In an older telling that shaped this product\'s thinking, the greatest teacher on the battlefield of the Gita was not the warrior but the charioteer — the sarathi — the one who steers so the student can focus on the fight. That is the whole ambition of this tool: to be the quiet charioteer of a child\'s attention. Not the hero. Not the warden. The steady hand on the reins during study hours, and invisible the rest of the time.',
  ];
  const closing = [
    'And one more belief, stated plainly because this industry rarely does: we will tell you what this product cannot do. A determined teenager can bypass any consumer software; we make bypassing unnecessary instead of impossible, and we document our limits in public. It doesn\'t teach your child mathematics — Khan Academy and NCERT do that beautifully; we make sure your child reaches them, and remembers them. It doesn\'t work on a phone in your child\'s hand — it protects the laptop where homework lives, and gives you the controls on your phone. Every boundary we state is a promise we can keep.',
    'We are a small team building this the way we\'d want it for our own children — who are, in fact, our first testers, our sharpest critics, and the names in our credits.',
  ];
  return React.createElement('div', { style: { padding: '72px 48px 96px', display: 'flex', justifyContent: 'center' } },
    React.createElement('div', { style: { maxWidth: 720, width: '100%', borderLeft: '3px solid var(--margin-red)', paddingLeft: 36 } },
      React.createElement('div', { style: { fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '.08em', fontSize: 12, color: 'var(--margin-red)' } }, 'Our philosophy'),
      React.createElement('h1', { style: { fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 38, color: 'var(--ink-navy)', margin: '10px 0 40px', lineHeight: 1.2 } }, 'Why we built a filter that teaches'),
      React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 28 } },
        paragraphs.map((p, i) => React.createElement('p', { key: i, style: { fontFamily: 'var(--font-body)', fontSize: 18, color: i % 2 === 1 && p.length < 80 ? 'var(--ink-navy)' : 'var(--muted-ink)', fontWeight: p.length < 80 ? 700 : 400, lineHeight: 1.7, margin: 0 } }, p))),
      React.createElement('div', { style: { margin: '40px 0', borderLeft: '3px solid var(--margin-red)', paddingLeft: 20, marginLeft: -36, paddingTop: 2, paddingBottom: 2 } },
        React.createElement('div', { style: { fontFamily: 'var(--font-body)', fontStyle: 'italic', fontSize: 19, color: 'var(--ink-navy)' } }, '"Rok-tok nahi — saarthi."')),
      React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 28, marginTop: 4 } },
        closing.map((p, i) => React.createElement('p', { key: i, style: { fontFamily: 'var(--font-body)', fontSize: 18, color: 'var(--muted-ink)', lineHeight: 1.7, margin: 0 } }, p))),
      React.createElement('div', { style: { marginTop: 48, fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 16, color: 'var(--ink-navy)' } }, '— The GuideRail team, Bengaluru & the family study table')));
}
window.About = { About };
